source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CoreDataManager_Example', :exclusive => true do
  pod "CoreDataManager", :path => "../"
end

target 'CoreDataManager_Tests', :exclusive => true do
  pod "CoreDataManager", :path => "../"

  
end
