source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'CoreDataManager_Example' do
  pod "CoreDataManager", :path => "../"
  
  target 'CoreDataManager_Tests' do
      inherit! :search_paths
  end
end
